---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rakeshdevops-app
  labels:
    app: rakeshdevops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rakeshdevops-app
  template:
    metadata:
      labels:
        app: rakeshdevops-app
    spec:
      containers:
      - name: rakeshdevops-container
        image: public.ecr.aws/p2j8v6t3/rakesh-devops-poc:latest
        ports:
        - containerPort: 3000
...
